# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messager_email',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(max_length=400),
        ),
    ]
