# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0002_auto_20170304_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(default='Hello', max_length=400),
        ),
        migrations.AlterField(
            model_name='message',
            name='messager_email',
            field=models.EmailField(default='noemail@noemail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='messager_name',
            field=models.CharField(default="What's Your name", max_length=30),
        ),
    ]
